name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  push: { branches: ["master", "main"] }
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          user: MeerBiene
          template: classic
          base: header, repositories, metadata
          config_timezone: America/New_York
          plugin_gists: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          plugin_lines: yes
          repositories_forks: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Display full year instead of half year
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKAPI_TOKEN }}
          plugin_wakatime_days: 30
          plugin_wakatime_sections: time, projects, projects-graphs, languages-graphs, languages
          plugin_wakatime_limit: 5
          plugin_wakatime_url: https://wakapi.stlf.me
          plugin_wakatime_user: meerbiene
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: mastered
          plugin_topics_limit: 0
